### ISSUE TITLE
Simplification

### ISSUE THREAD

**Issue by QwZhang** [bueler/p4pdes#51]
I think the following lines
https://github.com/bueler/p4pdes/blob/5f6aca9b94380549eb7744349635a92d0af787c7/c/ch4/reaction.c#L99-L110
can be rewritten as
```C
 } else {  // interior location 
     FF[i] = - u[i+1] + 2.0 * u[i] - u[i-1]; 
     R = - user->rho * PetscSqrtReal(u[i]); 
     x = i * h; 
     FF[i] -= h*h * (R + f_source(x)); 
 } 
```
which looks more concise and yields the same result.

**Comment by bueler** [comment]
I believe your change keeps the nonlinear system solution the same, and so it should work.  (Have you already tested it?)  In some cases there may be a (small) reduction in performance, but I have not tested it, and in many cases there will be no difference in performance.

The code is written this way because it has the effect of making the finite-difference (`-snes_fd_color`) Jacobian symmetric.  The same issue is addressed for the Poisson equation back in Chapter 3, in a paragraph just before Example 3.2 (page 49).  Does this make sense?

**Comment by QwZhang** [comment]
@bueler Thanks for your reply. I checked the modified code and it yielded the same result. I found the code can be simplified simply because it seems that FF[1] and FF[mx-2] are for internal grids and dose not need special treatment. Forgot it if I was wrong.
