### ISSUE TITLE
Dirichelet or Neumann BCs for a FVM discretizaton when using PETSc's SNES and TS

### ISSUE THREAD

**Issue by QwZhang** [bueler/p4pdes#52]
Hi, @bueler 

I have been struggling these days to implement a Dirichelet or Neumann BCs for a PDE in a structured, cell-centered finite volume discretizaton when using the SNES and Ts object in the PETSc framework. 

There are dosens of examples demonstrating way of BC setting with a finite difference medthod, e.g.,

https://github.com/bueler/p4pdes/blob/5f6aca9b94380549eb7744349635a92d0af787c7/c/ch4/reaction.c#L95-L98

https://github.com/bueler/p4pdes/blob/5f6aca9b94380549eb7744349635a92d0af787c7/c/ch5/heat.c#L153-L155

https://github.com/petsc/petsc/blob/386ebab930a846575609b49074a40c46e7f8ed75/src/ts/tutorials/ex26.c#L293-L343

which I think I have understood how they works.

But for a FVM discretizaton, I tried and found that the Dirichelet or Neumann BC can not be applied in these ways.

The only FVM example I found is the `advect.c` in `chap 11` of your book but it comes with a periodic BCs.

Could you give me a hint?

Best,
Qw

**Comment by bueler** [comment]
I am guessing you have seen Matt's comment on this question (https://lists.mcs.anl.gov/pipermail/petsc-users/2021-November/044970.html).

Setting Neumann (i.e. flux) boundary conditions should be easy and clear: a cell face of the first/last FV cell is (should be!) part of the boundary, and your Neumann condition determines the flux there.

The Dirichlet condition is more difficult, but Matt's ghost cells suggestion might be applied this way:  At the cell face on the boundary, set up an equation saying that the time derivative of the interpolated value at the boundary face is zero.  Then set the initial value of the ghost-cell center to be whatever is needed so that interpolation to the boundary face gives the desired value.  Thus you have added an unknown (the ghost cell center value) and a differential equation for it, with initial value.

**Comment by bueler** [comment]
See also LeVeque, _Finite Volume Methods for Hyperbolic Problems_, Cambridge U 2002.

**Comment by QwZhang** [comment]
Thanks for your help @bueler 
I used the ghost cells as you and LeVeque's book mentioned in the RHS function of TS, and the code behaves properly and yields the right results.
```C
...
//Dirichlet BC
u_A = -1.0;
u_B = 1.0; 
//Neumann BC, q = du/dx
q_A = 1.0;
q_B = -1.0; 
...
for (i = xs; i < xs + xm; i++) {
	if (i == 0) {
		//Dirichlet BC
		f[i] = (u[i+1] - 3*u[i] + 2*u_A)/dx/dx;

		//Neumann BC
		//f[i] = (u[i+1] - u[i] - q_A*dx)/dx/dx;

	} else if (i == mx - 1) {
		//Dirichlet BC
		//f[i] = (u[i-1] - 3.0*u[i] + 2.0*u_B) /dx/dx;

		//Neumann BC
		f[i] = (u[i-1] - u[i] + q_B*dx)/dx/dx;

	} else {
		f[i] = (u[i-1] - 2.0*u[i] + u[i+1]) / dx / dx;
	}
}
...
``
I attach a doc here to show the details:
[Diffusion_FV_derivation.pdf](https://github.com/bueler/p4pdes/files/7618143/Diffusion_FV_derivation.pdf)
`
